namespace Csfd
{
    public enum Genre
    {
        Akcni = 1,
        //Animovany = 3,
        //Dobrodruzny = 11,
        //Dokumentarni = 13,
        //Drama = 2,
        //Eroticky = 10,
        //Experimentalni = 26,
        //Fantasy = 4,
        //FilmNoir = 20,
        //Historicky = 21,
        //Horor = 5,
        //Hudebni = 22,
        //IMAX = 28,
        //Katastroficky = 39,
        //Komedie = 9,
        //Kratkometrazni = 14,
        //Krimi = 18,
        //Loutkovy = 23,
        //Muzikal = 12,
        //Mysteriozni = 16,
        //Podobenstvi = 25,
        //Poeticky = 27,
        //Pohadka = 30,
        //Povidkovy = 29,
        //Psychologicky = 31,
        //Publicisticky = 33,
        //RealityTV = 35,
        //Road = 40,
        //Rodinny = 6,
        //Romanticky = 15,
        //SciFi = 7,
        //Soutezni = 36,
        //Sportovni = 32,
        //TalkShow = 34,
        //Tanecni = 41,
        //Telenovela = 38,
        //Thriller = 8,
        //Valecny = 17,
        //Western = 19,
        //Zivotopisny = 37,

    }
}
